# Generated by Django 4.2 on 2025-12-30 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='Имя пользователя', max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Фамилия пользователя', max_length=150, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, help_text='Отчество пользователя', max_length=150, verbose_name='Отчество')),
                ('email', models.EmailField(db_index=True, help_text='Email адрес (используется для входа в систему)', max_length=254, unique=True, verbose_name='Email')),
                ('password_hash', models.CharField(help_text='Хеш пароля, созданный с помощью bcrypt', max_length=128, verbose_name='Хеш пароля')),
                ('is_active', models.BooleanField(default=True, help_text='Указывает, может ли пользователь войти в систему. Используется для мягкого удаления.', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('role', models.ForeignKey(help_text='Роль пользователя в системе', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='access.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users_user',
                'ordering': ['email'],
            },
        ),
    ]
