# Generated by Django 4.2 on 2025-12-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Указывает, может ли пользователь войти в админ-панель Django.', verbose_name='Персонал'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Указывает, что пользователь имеет все права без явного назначения.', verbose_name='Суперпользователь'),
        ),
    ]
