# Generated by Django 4.2 on 2025-12-30 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Уникальное название бизнес-элемента (например: users, products, orders)', max_length=100, unique=True, verbose_name='Название элемента')),
                ('description', models.TextField(blank=True, help_text='Описание элемента и его назначения в системе', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Бизнес-элемент',
                'verbose_name_plural': 'Бизнес-элементы',
                'db_table': 'access_businesselement',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Уникальное название роли (например: admin, manager, user)', max_length=100, unique=True, verbose_name='Название роли')),
                ('description', models.TextField(blank=True, help_text='Описание роли и её назначения в системе', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'access_role',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_permission', models.BooleanField(default=False, help_text='Разрешение на чтение собственных ресурсов', verbose_name='Чтение своих')),
                ('read_all_permission', models.BooleanField(default=False, help_text='Разрешение на чтение всех ресурсов', verbose_name='Чтение всех')),
                ('create_permission', models.BooleanField(default=False, help_text='Разрешение на создание ресурсов', verbose_name='Создание')),
                ('update_permission', models.BooleanField(default=False, help_text='Разрешение на обновление собственных ресурсов', verbose_name='Обновление своих')),
                ('update_all_permission', models.BooleanField(default=False, help_text='Разрешение на обновление всех ресурсов', verbose_name='Обновление всех')),
                ('delete_permission', models.BooleanField(default=False, help_text='Разрешение на удаление собственных ресурсов', verbose_name='Удаление своих')),
                ('delete_all_permission', models.BooleanField(default=False, help_text='Разрешение на удаление всех ресурсов', verbose_name='Удаление всех')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('element', models.ForeignKey(help_text='Элемент, к которому применяется правило', on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='access.businesselement', verbose_name='Бизнес-элемент')),
                ('role', models.ForeignKey(help_text='Роль, для которой применяется правило', on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='access.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Правило доступа',
                'verbose_name_plural': 'Правила доступа',
                'db_table': 'access_accessrule',
                'ordering': ['role', 'element'],
                'unique_together': {('role', 'element')},
            },
        ),
    ]
